import React, { useState } from "react";
import axios from "axios";
import router from "next/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// utils for login
import { login } from "../../utils/auth";
import { parseJWT } from "../../utils/parseJWT";

// parsing jwt for get the payload object

export default function Login() {
  const [email, setEmail] = useState([]);
  const [password, setPassword] = useState([]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const url = `${process.env.NEXT_PUBLIC_API_URL}/auth/login`;
      const response = await axios.post(url, { email, password });
      const { token } = response.data;
      await login({ token });
      const { role } = parseJWT(token);
      switch (role) {
        case 1:
          router.push("/admin/dashboard");
          break;
        case 2:
          router.push("/driver/dashboard");
          break;
        case 3:
          router.push("/member/dashboard");
          break;
        default:
          break;
      }
    } catch (error) {
      console.log("Error when redirecting into dashboard", error);
    }
  };

  return (
    <main className="form-signin mt-5 pt-5">
      <style jsx>{`
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        body {
          height: 100%;
          display: flex;
          align-items: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: #f5f5f5;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      `}</style>
      <Head>
        <title>Login|Simtya</title>
        <meta name="description" content="Generated by Login|Simtya" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit}>
        <Image
          className="mx-auto"
          src="/vercel.svg"
          alt=""
          width="72"
          height="72"></Image>
        <h1 className="h3 mb-3 fw-normal">Please sign in</h1>

        <div className="form-floating">
          <input
            name="email"
            onChange={(e) => {
              setEmail(e.target.value);
            }}
            type="email"
            className="form-control"
            id="floatingInput"
            placeholder="name@example.com"
          />
          <label htmlFor="floatingInput">Email Address</label>
        </div>
        <div className="form-floating">
          <input
            name="password"
            onChange={(e) => {
              setPassword(e.target.value);
            }}
            type="password"
            className="form-control"
            id="floatingPassword"
            placeholder="Password"
          />
          <label htmlFor="floatingPassword">Password</label>
        </div>

        <button className="w-100 btn btn-lg btn-primary" type="submit">
          Login
        </button>
      </form>
      <Link href="/auth/register">
        <a className="text-blueGray-200">
          <small>Are you member ? Create account here</small>
        </a>
      </Link>
    </main>
  );
}
