import React, { useState } from "react";
import axios from "axios";
import router from "next/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// Layouts file
import Auth from "../../layouts/Auth";

export default function Register() {
  const [username, setUsername] = useState([]);
  const [email, setEmail] = useState([]);
  const [password, setPassword] = useState([]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const url = `${process.env.NEXT_PUBLIC_API_URL}/auth/register`;
      await axios.post(url, {
        username,
        email,
        password,
      });
      router.push("/auth/login");
    } catch (error) {
      console.log("Error creating new user", error);
    }
  };
  return (
    <>
      <Head>
        <title>Register|Simtya</title>
        <meta name="description" content="Generated by Register|Simtya" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit}>
        <Image
          className="mx-auto"
          src="/vercel.svg"
          alt=""
          width="72"
          height="72"></Image>
        <h1 className="h3 mb-3 fw-normal">Please Register</h1>

        <div className="form-floating">
          <input
            name="email"
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            className="form-control"
            id="floatingInput"
            placeholder="name@example.com"
          />
          <label htmlFor="floatingInput">Email Address</label>
        </div>
        <div className="form-floating">
          <input
            name="username"
            onChange={(e) => setUsername(e.target.value)}
            type="text"
            className="form-control"
            id="floatingInput"
            placeholder="your unique username"
          />
          <label htmlFor="floatingInput">Username</label>
        </div>
        <div className="form-floating">
          <input
            name="password"
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            className="form-control"
            id="floatingPassword"
            placeholder="Password"
          />
          <label htmlFor="floatingPassword">Password</label>
        </div>

        <button className="w-100 btn btn-lg btn-primary" type="submit">
          Register
        </button>
      </form>
      <Link href="/auth/login">
        <a className="mt-2 fs-6 d-block">
          <small>Already have account? Sign in here</small>
        </a>
      </Link>
    </>
  );
}

Register.layout = Auth;
