import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div
      style={{ height: "100vh" }}
      className="d-flex text-center text-white bg-primary">
      <Head>
        <title>Welcome to Simtya</title>
        <meta name="description" content="Generated by Welcome to Simtya" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="cover-container
        d-flex
        w-100
        h-100
        p-3
        mx-auto
        flex-column">
        <header className="mb-auto">
          <div>
            <h3 className="float-md-start mb-0">Simtya</h3>
            <nav className="nav nav-masthead justify-content-center float-md-end">
              <a className="nav-link active" aria-current="page" href="#">
                Welcome
              </a>
            </nav>
          </div>
        </header>

        <main className="px-3">
          <h1>Transportation Management Apps</h1>
          <Image
            src="/vercel.svg"
            width="100"
            height="100"
            alt="logo-foundation"></Image>
          <p className="text-muted text-white-50 text-decoration-underline">
            Oetie Hermawan Foundation
          </p>
          <p className="lead">
            Manage your schedule, inventory, pickup service and many more with
            one apps. Getting notification about accidents and other event in
            your touch.
          </p>
          <p className="lead">
            <Link href="/auth/login">
              <a className="btn btn-lg btn-secondary fw-bold border-white bg-white">
                Login to Dashboard
              </a>
            </Link>
          </p>
        </main>

        <footer className="mt-auto text-white-50">
          <p>
            Copyright &copy;2021, by{" "}
            <a href="https://github.com/Wijayaac" className="text-white">
              Wijaya
            </a>
            .
          </p>
        </footer>
      </div>
    </div>
  );
}
